apiVersion: v1
kind: Service
metadata:
  name: flask-upload-server
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
  selector:
    app: flask-upload-server
